### ISSUE TITLE
test-signer issued credentials no longer verify

### ISSUE THREAD

**Issue by bmuramatsu** [jchartrand/test-signer#1]
A recent update to one or more libraries in the main DCC repo mean test-signer issued credentials no longer verify in the public VerifierPlus, as shared public links, or in the Android LCW.

**Comment by bmuramatsu** [comment]
Sample output from test-verifier. This is from April and the quickest that I could fine. Credentials issued end of June do the same thing.

[valid-dcc-demo.zip](https://github.com/jchartrand/test-signer/files/12016070/valid-dcc-demo.zip)

**Comment by jchartrand** [comment]
@bmuramatsu 

We just now discussed this on today's tech call. It is almost certainly that the OBv3 VCs produced by this app (and by the sign-and-verify installations for CU and SJCC) use the old OBv3 context:
```
"@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://purl.imsglobal.org/spec/ob/v3p0/context.json"
```

and VerifierPlus has recently been changed to use the newer versioned context:

https://purl.imsglobal.org/spec/ob/v3p0/context-3.0.1.json

The context was changed to allow newer issued credentials to validate.  Dmitri is going to update the DCC verifier library to accommodate both the old and the new contexts.

I can change this app to use the newer context, unless there is some reason you know of why I should leave it as-is?

**Comment by bmuramatsu** [comment]
From a test credential generation standpoint, I think we should support the current context.

Though I wonder if we should allow for the selection of a context in the credential generation? In other words make that a variable to put in the full URL of the context with the expectation that we support v1 VC, v2 VC when it comes out, and the various iterations of OBv3.

**Comment by jchartrand** [comment]
Hmmmm, yes, could do that, but any new context version will also require an update of the security-document-loader. Is the idea, though, not so much to support the latest and greatest context, but moreso to allow one to more easily generate credentials from a variety of context versions, say for example if you wanted to generate a credential for an older version of a wallet or something?

**Comment by bmuramatsu** [comment]
> to allow one to more easily generate credentials from a variety of context versions

Yes this is what I was thinking, there may be other contexts that we'll want to generate credentials in.

**Comment by kayaelle** [comment]
@jchartrand & @bmuramatsu - lets' talk about the role of this software as official DCC software so we can decide how it gets managed as part of our DCC workflows. We want to create a demo app or and/or add this functionality to the sandbox but need to plan that. Ideally we have one set of software that produces test credentials to minimize maintenance and updates. I'll add this to dev discussion. 

If this still needs to be updated for short-term needs, when is it needed by? Thanks

**Comment by bmuramatsu** [comment]
Short term, given our discussion this morning I think the following updates are needed:

- both test-signer and security-document-loader need to be updated for OBv3.0.2
- test-signer should be updated to support markdown in at least the Criteria field, and potentially the Description field

**Comment by kayaelle** [comment]
Thanks @bmuramatsu. I'll create issues to: 

1. Move this repo to DCC org

then will submit issues to

1. Update Context
2. Review if test signer can support markdown

**Comment by kayaelle** [comment]
#1 already done! I just noticed. Thanks @jchartrand!

**Comment by bmuramatsu** [comment]
@kayaelle I think we need to update to 3.0.2...

**Comment by kayaelle** [comment]
New issues have been created to updated context to 3.0.2, add markdown functionality, add option to choose a context. 

Will close this issue an d follow up in the subsequent ones.
